namespace le0zh.Infrastructure.Data.Core
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kb.DataAccess.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FilterExpression cannot be null.
        /// </summary>
        public static string exception_FilterCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("exception_FilterCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PageIndex is less than zero.
        /// </summary>
        public static string exception_InvalidPageIndex
        {
            get
            {
                return ResourceManager.GetString("exception_InvalidPageIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PageSize is less than zero.
        /// </summary>
        public static string exception_InvalidPageSize
        {
            get
            {
                return ResourceManager.GetString("exception_InvalidPageSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OrderByExpress cannot be null.
        /// </summary>
        public static string exception_OrderByExpressionCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("exception_OrderByExpressionCannotBeNull", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specification cannot be null.
        /// </summary>
        public static string exception_SpecificationIsNull
        {
            get
            {
                return ResourceManager.GetString("exception_SpecificationIsNull", resourceCulture);
            }
        }
    }
}
